{% set version = "1.3.4" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://github.com/storpipfugl/pykdtree/archive/v{{ version }}.tar.gz
  sha256: d4061e5b77f8c6c87a803346fe620e0eee13e15dd5fef88c48cc217c58ff6510

build:
  number: 1
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - cython pykdtree/kdtree.pyx
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - msinttypes  # [win and py<35]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pykdtree

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Fast kd-tree implementation with OpenMP-enabled queries

extra:
  recipe-maintainers:
    - ocefpaf
