{% set version = "1.3.12" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: cc20b2a67c64056485a314d2c2b6dba354af7ee1c8fb8dae1be6f2936a374341

build:
  number: 2
  skip: true  # [py<39]
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
    - numpy
    - cython
  run:
    - python

test:
  imports:
    - pykdtree

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Fast kd-tree implementation with OpenMP-enabled queries

extra:
  recipe-maintainers:
    - djhoese
    - ocefpaf
    - ngam
    - mraspaud
