{% set version = "1.3.6" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: 780b693d0555b857d7aab31e35d4293bf4ebdb9dec7a45ba4bb23b4400f626dc

build:
  number: 1
  script:
    - export USE_OMP=1  # [linux]
    - export USE_OMP=0  # [osx]
    - set USE_OMP=0  # [win]
    - cython pykdtree/kdtree.pyx  # [not (osx and (build_platform != target_platform))]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:
    - python
    - pip
    - numpy
    - cython
    - msinttypes  # [win and py<35]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pykdtree

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Fast kd-tree implementation with OpenMP-enabled queries

extra:
  recipe-maintainers:
    - djhoese
    - ocefpaf
    - ngam
    - mraspaud
