{% set version = "1.4.2" %}

package:
  name: pykdtree
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pykdtree/pykdtree-{{ version }}.tar.gz
  sha256: bd2b967a16a5510efa873ee52d959d0d821389cc749bb51673ae68316eeb65f5

build:
  number: 0
  skip: true  # [py<39]
  script:
    - export USE_OMP=1  # [linux or osx]
    - set USE_OMP=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - llvm-openmp  # [osx or win]
    - libgomp  # [linux]
  host:
    - python
    - setuptools
    - pip
    - numpy
    - cython
    - llvm-openmp  # [osx or win]
    - libgomp  # [linux]
  run:
    - python

test:
  imports:
    - pykdtree

about:
  home: https://pypi.python.org/pypi/pykdtree
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: Fast kd-tree implementation with OpenMP-enabled queries

extra:
  recipe-maintainers:
    - djhoese
    - ocefpaf
    - ngam
    - mraspaud
